apiVersion: v1
kind: Service
metadata:
  name: pdf-slurper
  namespace: pdf-slurper
  labels:
    app: pdf-slurper
spec:
  type: NodePort  # NodePort for local access
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # Access on localhost:30080
      protocol: TCP
      name: http
  selector:
    app: pdf-slurper
---
# Alternative LoadBalancer service for easier access (OrbStack supports this)
apiVersion: v1
kind: Service
metadata:
  name: pdf-slurper-lb
  namespace: pdf-slurper
  labels:
    app: pdf-slurper
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: pdf-slurper
