apiVersion: v1
kind: List
metadata:
  name: pdf-slurper-crud-deployment
items:
  # ConfigMap for application configuration
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: pdf-slurper-config
      labels:
        app: pdf-slurper
        version: v2-crud
    data:
      PDF_SLURPER_ENV: "production"
      PDF_SLURPER_USE_NEW: "true"
      PDF_SLURPER_HOST: "0.0.0.0"
      PDF_SLURPER_PORT: "8080"
      WEB_UI_PORT: "3000"
      LOG_LEVEL: "INFO"
      API_DOCS_ENABLED: "true"
      ENABLE_CRUD: "true"
      WORKERS: "2"
      DATABASE_URL: "sqlite:////data/pdf_slurper.db"

  # PersistentVolumeClaim for data persistence
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pdf-slurper-data-v2
      labels:
        app: pdf-slurper
        version: v2-crud
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi  # Increased for CRUD operations

  # ImageStream
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: pdf-slurper
      labels:
        app: pdf-slurper
    spec:
      lookupPolicy:
        local: true

  # Deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: pdf-slurper-v2
      labels:
        app: pdf-slurper
        version: v2-crud
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: pdf-slurper
          version: v2-crud
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
      template:
        metadata:
          labels:
            app: pdf-slurper
            version: v2-crud
        spec:
          containers:
            - name: pdf-slurper
              image: image-registry.openshift-image-registry.svc:5000/NAMESPACE/pdf-slurper:v2-crud
              imagePullPolicy: Always
              ports:
                - containerPort: 8080
                  protocol: TCP
                  name: api
                - containerPort: 3000
                  protocol: TCP
                  name: web
              envFrom:
                - configMapRef:
                    name: pdf-slurper-config
                - secretRef:
                    name: pdf-slurper-secret
              volumeMounts:
                - name: data
                  mountPath: /data
                - name: uploads
                  mountPath: /app/uploads
                - name: logs
                  mountPath: /app/logs
              resources:
                requests:
                  memory: "256Mi"
                  cpu: "100m"
                limits:
                  memory: "1Gi"  # Increased for CRUD operations
                  cpu: "500m"
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 30
                periodSeconds: 30
                timeoutSeconds: 5
                failureThreshold: 3
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                initialDelaySeconds: 10
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 3
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: pdf-slurper-data-v2
            - name: uploads
              emptyDir: {}
            - name: logs
              emptyDir: {}

  # Service
  - apiVersion: v1
    kind: Service
    metadata:
      name: pdf-slurper-v2
      labels:
        app: pdf-slurper
        version: v2-crud
    spec:
      ports:
        - name: api
          port: 8080
          targetPort: 8080
          protocol: TCP
        - name: web
          port: 3000
          targetPort: 3000
          protocol: TCP
      selector:
        app: pdf-slurper
        version: v2-crud
      type: ClusterIP

  # Route for external access
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: pdf-slurper-v2
      labels:
        app: pdf-slurper
        version: v2-crud
    spec:
      host: pdf-slurper-NAMESPACE.apps.openshift.example.com
      port:
        targetPort: web
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      to:
        kind: Service
        name: pdf-slurper-v2
        weight: 100

  # HorizontalPodAutoscaler for scaling
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: pdf-slurper-v2-hpa
      labels:
        app: pdf-slurper
        version: v2-crud
    spec:
      scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: pdf-slurper-v2
      minReplicas: 1
      maxReplicas: 3
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 70
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 80
