# OpenShift Secret Configuration
# WARNING: This is a TEMPLATE. Never commit actual secret values!
# Use this template to create actual secrets in OpenShift
apiVersion: v1
kind: Secret
metadata:
  name: pdf-slurper-secrets
  namespace: dept-barc
type: Opaque
stringData:
  # Replace these with actual values when deploying
  API_KEY: "REPLACE_WITH_ACTUAL_API_KEY"
  JWT_SECRET: "REPLACE_WITH_ACTUAL_JWT_SECRET"
  SECRET_KEY: "REPLACE_WITH_ACTUAL_SECRET_KEY"
  DATABASE_URL: "sqlite:////app/data/pdf_slurper.db"
